Watching for file changes with StatReloader
[28/Jul/2024 18:40:26] "GET / HTTP/1.1" 200 4551
[28/Jul/2024 18:40:26] "GET / HTTP/1.1" 200 4551
Not Found: /favicon.ico
WARNING:django.request:Not Found: /favicon.ico
[28/Jul/2024 18:40:30] "GET /favicon.ico HTTP/1.1" 404 2454
[28/Jul/2024 18:47:48] "GET / HTTP/1.1" 200 4765
[28/Jul/2024 18:49:25] "GET / HTTP/1.1" 200 4751
[28/Jul/2024 18:54:46] "GET / HTTP/1.1" 200 4982
[28/Jul/2024 18:55:31] "GET / HTTP/1.1" 200 4982
[28/Jul/2024 18:56:21] "GET / HTTP/1.1" 200 4982
[28/Jul/2024 18:59:21] "GET / HTTP/1.1" 200 4982
[28/Jul/2024 18:59:29] "GET /dashboard/cashier-farmers/ HTTP/1.1" 200 39075
[28/Jul/2024 18:59:33] "GET / HTTP/1.1" 200 4982
[28/Jul/2024 18:59:36] "GET / HTTP/1.1" 200 4982
[28/Jul/2024 19:22:31] "GET / HTTP/1.1" 200 5876
[28/Jul/2024 19:23:21] "GET / HTTP/1.1" 200 5677
[28/Jul/2024 19:24:24] "GET /dashboard/cashier-login/ HTTP/1.1" 200 1060
[28/Jul/2024 19:24:28] "POST /dashboard/cashier-login/ HTTP/1.1" 302 0
[28/Jul/2024 19:24:29] "GET /dashboard/select_harvest/ HTTP/1.1" 200 1950
[28/Jul/2024 19:24:31] "POST /dashboard/select_harvest/ HTTP/1.1" 302 0
[28/Jul/2024 19:24:31] "GET /dashboard/cashier-dashboard/ HTTP/1.1" 200 2216
[28/Jul/2024 19:24:39] "GET /dashboard/cashier-farmers/ HTTP/1.1" 200 39075
[28/Jul/2024 19:25:18] "GET / HTTP/1.1" 200 5677
[28/Jul/2024 19:25:21] "GET /board/admin_login/ HTTP/1.1" 200 1056
[28/Jul/2024 19:25:26] "POST /board/admin_login/ HTTP/1.1" 302 0
[28/Jul/2024 19:25:26] "GET /board/admin_dashboard/ HTTP/1.1" 200 8262
[28/Jul/2024 19:25:33] "GET /board/admin_dashboard/?search_query=Hal HTTP/1.1" 200 8342
[28/Jul/2024 19:25:44] "GET /board/admin_dashboard/?search_query=Hay HTTP/1.1" 200 8540
[28/Jul/2024 19:25:48] "GET /board/edit_farmer/486/ HTTP/1.1" 200 3653
Internal Server Error: /board/edit_farmer/486/
Traceback (most recent call last):
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\query.py", line 948, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
dashboard.models.MbuniWeight.DoesNotExist: MbuniWeight matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: dashboard_mbuniweight.weight

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\board\views.py", line 291, in edit_farmer
    mbuni_weight, created = MbuniWeight.objects.get_or_create(field=field)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\query.py", line 955, in get_or_create
    return self.create(**params), True
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\base.py", line 1071, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\base.py", line 1112, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: dashboard_mbuniweight.weight
ERROR:django.request:Internal Server Error: /board/edit_farmer/486/
Traceback (most recent call last):
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\query.py", line 948, in get_or_create
    return self.get(**kwargs), False
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\query.py", line 649, in get
    raise self.model.DoesNotExist(
dashboard.models.MbuniWeight.DoesNotExist: MbuniWeight matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.IntegrityError: NOT NULL constraint failed: dashboard_mbuniweight.weight

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\contrib\auth\decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\board\views.py", line 291, in edit_farmer
    mbuni_weight, created = MbuniWeight.objects.get_or_create(field=field)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\query.py", line 955, in get_or_create
    return self.create(**params), True
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\base.py", line 1071, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\base.py", line 1112, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: NOT NULL constraint failed: dashboard_mbuniweight.weight
[28/Jul/2024 19:28:47] "POST /board/edit_farmer/486/ HTTP/1.1" 500 187543
[28/Jul/2024 19:28:57] "GET /dashboard/cashier-farmers/ HTTP/1.1" 200 39073
[28/Jul/2024 19:32:31] "GET /dashboard/cashier-dashboard/ HTTP/1.1" 200 2184
[28/Jul/2024 19:32:59] "GET /dashboard/manage_harvests/ HTTP/1.1" 200 6257
[28/Jul/2024 19:34:11] "GET /dashboard/manage_harvests/ HTTP/1.1" 200 6275
[28/Jul/2024 19:34:51] "GET /board/admin_dashboard/ HTTP/1.1" 200 8262
C:\Users\Owner\Documents\olmismis\dashboard\urls.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Owner\Documents\olmismis\dashboard\urls.py changed, reloading.
Performing system checks...

System check identified no issues (0 silenced).
July 28, 2024 - 18:40:21
Django version 5.0.6, using settings 'project_settings.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\management\base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\urls\resolvers.py", line 519, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Owner\Documents\olmismis\project_settings\urls.py", line 24, in <module>
    path('dashboard/', include('dashboard.urls')),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\urls\conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Owner\Documents\olmismis\dashboard\urls.py", line 25, in <module>
    path('cashier_edit_weight/', views.cashier_edit_weight, name='cashier_edit_weight'),  # URL for editing weig
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'dashboard.views' has no attribute 'cashier_edit_weight'
C:\Users\Owner\Documents\olmismis\dashboard\forms.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Owner\Documents\olmismis\dashboard\forms.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\management\base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\urls\resolvers.py", line 519, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Owner\Documents\olmismis\project_settings\urls.py", line 24, in <module>
    path('dashboard/', include('dashboard.urls')),
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\urls\conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Owner\Documents\olmismis\dashboard\urls.py", line 25, in <module>
    path('cashier_edit_weight/', views.cashier_edit_weight, name='cashier_edit_weight'),  # URL for editing weig
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'dashboard.views' has no attribute 'cashier_edit_weight'
C:\Users\Owner\Documents\olmismis\dashboard\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Owner\Documents\olmismis\dashboard\views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\management\base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\urls\resolvers.py", line 519, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Owner\Documents\olmismis\project_settings\urls.py", line 19, in <module>
    from dashboard import views
  File "C:\Users\Owner\Documents\olmismis\dashboard\views.py", line 20, in <module>
    from board.models import  EditRequest
ImportError: cannot import name 'EditRequest' from 'board.models' (C:\Users\Owner\Documents\olmismis\board\models.py)
C:\Users\Owner\Documents\olmismis\board\models.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Owner\Documents\olmismis\board\models.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\management\commands\runserver.py", line 133, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\management\base.py", line 486, in check
    all_issues = checks.run_checks(
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\checks\registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    return check_method()
           ^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\urls\resolvers.py", line 519, in check
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\urls\resolvers.py", line 738, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\urls\resolvers.py", line 731, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Owner\Documents\olmismis\project_settings\urls.py", line 25, in <module>
    path('board/', include('board.urls')),
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\Documents\olmismis\venv\Lib\site-packages\django\urls\conf.py", line 39, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Owner\Documents\olmismis\board\urls.py", line 13, in <module>
    path('admin/edit-requests/', views.admin_edit_requests, name='admin_edit_requests'),
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'board.views' has no attribute 'admin_edit_requests'
C:\Users\Owner\Documents\olmismis\board\views.py changed, reloading.
INFO:django.utils.autoreload:C:\Users\Owner\Documents\olmismis\board\views.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
[29/Jul/2024 12:37:55] "GET /board/admin_dashboard/ HTTP/1.1" 200 8332
[29/Jul/2024 12:38:01] "GET /board/admin/edit-requests/ HTTP/1.1" 200 1387
[29/Jul/2024 12:38:26] "GET / HTTP/1.1" 200 5677
[29/Jul/2024 12:40:10] "GET / HTTP/1.1" 200 5718
[29/Jul/2024 12:41:26] "GET / HTTP/1.1" 200 5731
[29/Jul/2024 12:42:39] "GET /dashboard/cashier-login/ HTTP/1.1" 200 1060
ERROR:dashboard.views:Authentication failed
[29/Jul/2024 12:42:43] "POST /dashboard/cashier-login/ HTTP/1.1" 200 1060
[29/Jul/2024 12:42:48] "GET /dashboard/cashier-signup/ HTTP/1.1" 200 1184
[29/Jul/2024 12:42:55] "POST /dashboard/cashier-signup/ HTTP/1.1" 302 0
[29/Jul/2024 12:42:55] "GET /dashboard/cashier-login/ HTTP/1.1" 200 1060
[29/Jul/2024 12:43:00] "POST /dashboard/cashier-login/ HTTP/1.1" 302 0
[29/Jul/2024 12:43:00] "GET /dashboard/select_harvest/ HTTP/1.1" 200 1950
[29/Jul/2024 12:43:03] "POST /dashboard/select_harvest/ HTTP/1.1" 302 0
[29/Jul/2024 12:43:03] "GET /dashboard/cashier-dashboard/ HTTP/1.1" 200 2390
[29/Jul/2024 12:43:08] "GET /dashboard/cashier-farmers/ HTTP/1.1" 200 39073
[29/Jul/2024 12:43:12] "GET /dashboard/cashier-dashboard/ HTTP/1.1" 200 2023
[29/Jul/2024 12:43:14] "GET /dashboard/cashier_edit_weight/ HTTP/1.1" 200 2936
[29/Jul/2024 12:43:23] "GET /dashboard/cashier-farmers/ HTTP/1.1" 200 39073
[29/Jul/2024 12:43:43] "GET /dashboard/cashier-dashboard/ HTTP/1.1" 200 2023
[29/Jul/2024 12:43:45] "GET /dashboard/cashier_edit_weight/ HTTP/1.1" 200 2936
[29/Jul/2024 12:43:56] "POST /dashboard/cashier_edit_weight/ HTTP/1.1" 302 0
[29/Jul/2024 12:43:56] "GET /dashboard/cashier-dashboard/ HTTP/1.1" 200 2271
[29/Jul/2024 12:44:04] "GET /board/admin/edit-requests/ HTTP/1.1" 200 1863
[29/Jul/2024 12:44:44] "GET /board/admin/reject-request/1/ HTTP/1.1" 302 0
[29/Jul/2024 12:44:44] "GET /board/admin/edit-requests/ HTTP/1.1" 200 1387
[29/Jul/2024 12:44:52] "GET /dashboard/cashier-farmers/ HTTP/1.1" 200 39073
[29/Jul/2024 12:45:01] "GET /dashboard/cashier-farmers/ HTTP/1.1" 200 39073
